create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  title text not null,
  brief text not null,
  objective text not null default 'ventas',
  status text not null default 'draft' check (status in ('draft', 'approved', 'scheduled', 'published', 'archived')),
  publish_as_offer boolean not null default false,
  scheduled_for timestamptz,
  created_by uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.campaign_assets (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.campaigns(id) on delete cascade,
  provider text not null,
  asset_type text not null check (asset_type in ('image', 'video', 'audio', 'copy')),
  content_url text,
  copy_text text,
  duration_seconds integer,
  is_approved boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.scheduled_publications (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.campaigns(id) on delete cascade,
  channel text not null,
  scheduled_for timestamptz not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'published', 'failed', 'cancelled')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_campaign_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_campaigns_updated_at on public.campaigns;
create trigger trg_campaigns_updated_at
before update on public.campaigns
for each row execute function public.set_campaign_updated_at();

alter table public.campaigns enable row level security;
alter table public.campaign_assets enable row level security;
alter table public.scheduled_publications enable row level security;

create policy "Admins manage campaigns"
on public.campaigns
for all
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy "Admins manage campaign assets"
on public.campaign_assets
for all
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy "Admins manage scheduled publications"
on public.scheduled_publications
for all
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');
