# Generated by Django 5.2.17 on 2026-10-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("role", models.TextField()),
            ],
            options={
                "verbose_name": "perfil",
                "verbose_name_plural": "perfiles",
                "db_table": "profiles",
                "managed": False,
            },
        ),
    ]
