# Generated by Django 5.2.17 on 2026-09-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="nombre")),
                ("slug", models.TextField(verbose_name="slug")),
                (
                    "image_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="URL de imagen"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "order",
                    models.IntegerField(
                        db_column="order", default=0, verbose_name="orden"
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "db_table": "categories",
                "ordering": ["order", "name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="descripción"),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="precio por kg"
                    ),
                ),
                (
                    "price_per_lb",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Calculado automáticamente a partir del precio por kg.",
                        max_digits=10,
                        verbose_name="precio por lb",
                    ),
                ),
                (
                    "image_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="URL de imagen"
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="inventario")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="creado el"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
                (
                    "min_quantity_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="cantidad mínima (kg)",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "db_table": "products",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CutSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avg_piece_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="P-20: habilita el modo de carrito por piezas.",
                        max_digits=10,
                        null=True,
                        verbose_name="peso promedio por pieza (kg)",
                    ),
                ),
                (
                    "thickness_min_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="grosor mínimo (in)",
                    ),
                ),
                (
                    "thickness_max_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="grosor máximo (in)",
                    ),
                ),
                (
                    "thickness_default_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="grosor por defecto (in)",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="proveedor"
                    ),
                ),
                (
                    "presentation",
                    models.CharField(
                        blank=True,
                        choices=[("piece", "Pieza"), ("package", "Paquete")],
                        max_length=20,
                        verbose_name="presentación",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec",
                        to="inventory.product",
                        verbose_name="producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "especificación de corte",
                "verbose_name_plural": "especificaciones de corte",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("thickness_min_in__isnull", True),
                            ("thickness_max_in__isnull", True),
                            ("thickness_min_in__lte", models.F("thickness_max_in")),
                            _connector="OR",
                        ),
                        name="cutspec_thickness_min_lte_max",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("thickness_default_in__isnull", True),
                            ("thickness_min_in__isnull", True),
                            ("thickness_default_in__gte", models.F("thickness_min_in")),
                            _connector="OR",
                        ),
                        name="cutspec_thickness_default_gte_min",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("thickness_default_in__isnull", True),
                            ("thickness_max_in__isnull", True),
                            ("thickness_default_in__lte", models.F("thickness_max_in")),
                            _connector="OR",
                        ),
                        name="cutspec_thickness_default_lte_max",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("avg_piece_weight_kg__isnull", True),
                            ("avg_piece_weight_kg__gte", 0),
                            _connector="OR",
                        ),
                        name="cutspec_avg_piece_weight_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("thickness_min_in__isnull", True),
                            ("thickness_min_in__gte", 0),
                            _connector="OR",
                        ),
                        name="cutspec_thickness_min_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("thickness_max_in__isnull", True),
                            ("thickness_max_in__gte", 0),
                            _connector="OR",
                        ),
                        name="cutspec_thickness_max_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("thickness_default_in__isnull", True),
                            ("thickness_default_in__gte", 0),
                            _connector="OR",
                        ),
                        name="cutspec_thickness_default_non_negative",
                    ),
                ],
            },
        ),
    ]
