# Generated by Django 5.2.17 on 2026-10-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "product_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("product_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "favorito",
                "verbose_name_plural": "favoritos",
                "db_table": "favorites",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "ítem de pedido",
                "verbose_name_plural": "ítems de pedido",
                "db_table": "order_items",
                "managed": False,
            },
        ),
    ]
